name: Code Quality Checks

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm install
      - run: npm audit fix

      - run: npm run format
      - run: npm run format-check # Change format:check -> format-check
      - run: npm run spell-check
      - run: npm run lint-ls # Change lint:ls -> lint-ls
      - run: npm run lint-md
