name: Code Quality Checks

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm install

      - run: npm run format:check
      - run: npm run spell-check
      - run: npm run lint:ls
      - run: npm run lint:md
